---
- name: Check Secrets 
  hosts: all
  become: true
  
  tasks:

    - name: Read Secrets
      debug:
        var: item
      loop:
        - "{{ db_user }}"  
        - "{{ db_password }}"
        - "{{ api }}"

    