#cloud-config
users:
  - name: ${username}
    groups: sudo,wheel
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - ${ssh_key}

  - name: backup
    sudo: ALL=(ALL) NOPASSWD:ALL       # Allow use sudo command without entring password
    shell: /bin/bash
    password: "maxik257752"
    lock_passwd: false 

write_files:
  - path: /etc/ssh/sshd_config.d/99-cloud-init.conf
    content: |
      PermitRootLogin yes
      PasswordAuthentication yes
      ChallengeResponseAuthentication no
      UsePAM yes
    append: true

runcmd:
  - setenforce 0
  - sed -i 's/^SELINUX=enforcing/SELINUX=permissive/' /etc/selinux/config
  - systemctl stop firewalld
  - systemctl disable firewalld
  - dnf update -y
  - dnf install -y openssh-server python3
  - systemctl enable --now sshd
