# IF PROMETHEUS GETS METRICS ITSSELF
# scrape_configs:
#   - job_name: 'victoriametrics'
#     static_configs:
#       - targets: ['victoriametrics:8428']
# global:
#   scrape_interval: 10s
# scrape_configs:
#   - job_name: 'exporter1'
#     static_configs:
#       - targets: ['158.160.35.129:9100']

#   - job_name: 'exporter2'
#     static_configs:
#       - targets: ['89.169.136.80:9100']



# WHERE TO SEND ALERTS?
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'


rule_files:
  - "rules.yml"