# WHERE TO GET METRICS FROM?
global:
  scrape_interval: 10s

###
# MANUALLY + FILTERING BY JOB'S NAME. FOR EXAMPLE:  (1) {job="cpu_instances"}
###

# scrape_configs:
#   - job_name: 'cpu_instances'
#     static_configs:
#       - targets: ['158.160.35.129:9100']

#   - job_name: 'vm_instances'
#     static_configs:
#       - targets: ['89.169.136.80:9100']


###
# DYNAMIC FILTERING TARGETS(VMS) BY USING TAGS. FOR EXAMPLE:  (1) YandexCloud:  metric: cpu|vm  (2) rules.yml:  by(instance)  (3) param..{metric="cpu"}  
###

scrape_configs:
  - job_name: instances
    yandexcloud_sd_configs:
      - service: compute
        yandex_passport_oauth_token: "y0_AgAAAABuzFxNAATuwQAAAAEW1GWdAACDtg5vCthLe603VZW8ixNFHBndGg"
    relabel_configs:
      - source_labels: [__meta_yandexcloud_instance_label_metric]                                               # Get label "metric" from YC. 
        target_label: "metric"                                                                                  # name of existed/new label in Prometheus
        replacement: "$1"                                                                                       # get value of label "metric_type" from every vm and write: 

      - source_labels: [__meta_yandexcloud_instance_public_ip_0]                                                # get public_ip
        target_label: __address__
        replacement: "$1:9100"

      
      

