services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # restart: unless-stopped

  promtail:
    image: grafana/promtail
    container_name: promtail
    ports:
      - "9080:9080" # this is only needed if you are going to send syslogs
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml
      - /var/log:/var/log # get access to vm logs(not only container logs)
    command: 
      - '--config.file=/etc/promtail/promtail.yml'
    # restart: unless-stopped

  loki:
    image: grafana/loki
    container_name: loki
    user: "0"
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/etc/loki/loki.yml
    command: 
      - '--config.file=/etc/loki/loki.yml'
    # restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports: 
      - "3000:3000"