all:
  children:
    k8s:
      hosts:
        master: {}
        worker1: {}
        worker2: {}
    k8s_master:
      hosts:
        master: {}
    k8s_worker:
      hosts:
        worker1: {}
        worker2: {}
    yandex_dynamic:
      hosts:
        master: {}
        worker1: {}
        worker2: {}
  hosts:
    master:
      ansible_host: 158.160.52.53
    worker1:
      ansible_host: 89.169.153.124
    worker2:
      ansible_host: 89.169.153.56
