---
- name: Deploy node-exporter to gain well-formatted logs for Prometheus or another logging system
  hosts: all
  become: true
  roles: 
    - docker_install
  tasks:
    - name: Deploy only
      tags: deploy
      block:
          - name: Pull node-exporter Docker image
            docker_image:
              name: prom/node-exporter
              source: pull

          - name: Run node-exporter container
            docker_container:
              name: node-exporter
              image: prom/node-exporter
              state: started
              restart_policy: always
              published_ports:
                - "9100:9100"